name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./lab1/app_python/requirements.txt

    - name: Lint with flake8
      run: flake8 ./lab1/app_python/.

    - name: Test with pytest
      run: pytest ./lab1/app_python/test.py