name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./lab1/app_python/requirements.txt

    - name: Lint with flake8
      run: flake8 ./lab1/app_python/.

    - name: Test with pytest
      run: pytest ./lab1/app_python/test.py


    - name: Login to Docker registry
      uses: docker/login-action@v3
      with:
        registry: https://hub.docker.com
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t dev-ops-lab-3 ./lab1/

    - name: Push Docker image
      run: docker push hephzibah301/dev-ops-lab-3:latest